
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c  " python manage.py wait_for_db && \
            python manage.py migrate && \
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=svddevdb
      - DB_USER=svddevuser
      - DB_PASS=svddevpostgres
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    volumes:
      - svd-dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=svddevdb
      - POSTGRES_USER=svddevuser
      - POSTGRES_PASSWORD=svddevpostgres


volumes:
  svd-dev-db-data:
  dev-static-data: