# Generated by Django 5.1.2 on 2024-10-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svduser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email valid for the User of the this website'),
        ),
    ]
