# Generated by Django 5.1.3 on 2024-11-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_birth_gender_member_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='svduser',
            name='birthday',
            field=models.DateField(default='1916-09-23', verbose_name='Birthday of the user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='svduser',
            name='name',
            field=models.CharField(default='', max_length=47, verbose_name='First or Lastname'),
        ),
    ]
