# Generated by Django 5.1.3 on 2024-11-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_svduser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svduser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday of the user'),
        ),
    ]
