# Generated by Django 5.1.3 on 2024-11-16 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_svduser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='father',
            field=models.ForeignKey(blank=True, help_text='If not known leave it blank!', limit_choices_to={'sex': 'M'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_query_name='bio_father', to='core.member', verbose_name='Biological father'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mother',
            field=models.ForeignKey(blank=True, help_text='If not known leave it blank!', limit_choices_to={'sex': 'F'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bio_mother', to='core.member', verbose_name='Biological mother'),
        ),
    ]
