# Generated by Django 5.1.6 on 2025-02-13 08:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_member_image_alter_member_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.member_image_filepath),
        ),
    ]
