# Generated by Django 5.1.6 on 2025-03-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='svduser',
            name='access',
            field=models.CharField(choices=[('NO', 'No access to family data.'), ('PRO', 'Read only data from departed people.'), ('PRW', 'Read write data departed people.'), ('RO', 'Read all family data.'), ('RW', 'Full access to family data.')], db_comment='Can only be changed by superuser.', default='PRO', help_text='Can only be changed by superuser.', max_length=3, verbose_name='Gender by birth'),
        ),
    ]
