# Generated by Django 5.1.6 on 2025-02-22 14:12

import core.models
import django.db.models.deletion
import famTree.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_alter_member_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=15, verbose_name='Event type')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(choices=famTree.models.get_event_types, max_length=15)),
                ('date', models.DateField(verbose_name='Date of the event')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date of the event')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.member_image_filepath)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member')),
                ('source', models.ManyToManyField(to='famTree.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name of the location')),
                ('city', models.CharField(blank=True, max_length=15, null=True, verbose_name='Name of the town')),
                ('street', models.CharField(blank=True, max_length=127, null=True, verbose_name='Street')),
                ('number', models.CharField(blank=True, max_length=15, null=True, verbose_name='House or Apartment number')),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(default='Netherlands', max_length=15, verbose_name='Country')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Longitude')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Latitude')),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='famTree.event')),
            ],
        ),
    ]
