# Generated by Django 5.1.6 on 2025-02-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famTree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Name of the town'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=31, unique=True, verbose_name='Name of the location'),
        ),
    ]
