# Generated by Django 5.1.6 on 2025-03-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_member_image'),
        ('famTree', '0002_alter_location_city_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member'),
        ),
    ]
